name: ci-workflows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-run-rake:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version: [2.2, 2.3, 2.4, 2.5, 2.6, 2.7]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2

    - name: "setup-ruby"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # automatically caches and installs gems

    - name: "run-rake-scripts"
      run: bundle exec rake
